### ISSUE TITLE
Add 'checkbulk' API

### ISSUE THREAD

**Issue by AlexeyRaga** [JalexSocial/SpiceDb#11]
SpiceDB now has the ability to bulk-check permissions.
It'd be valuable to have this ability from the .NET bindings as well

<img width="946" alt="image" src="https://github.com/JalexSocial/SpiceDb/assets/1394391/bad82317-d617-4d5c-ac72-6b8169334dd5">

**Comment by amadard** [comment]
Adding my voice to this, it would be great to have this added.

**Comment by tanczosm** [comment]
That is a very interesting addition as it's a pain to have to check permissions one at a time when often you might have multiple permissions in use in one particular area of an application.  I started a branch to work on implementing this method.  The proto definitions are up to date in the branch and I just have to add the method to do it.  

I'm not super happy with the internals of this library at the moment.. I'd like to line it up with the api a bit better so I may at least refactor a bit.

**Comment by tanczosm** [comment]
I added this in #13 but unfortunately I can't test it through serverless as the experimental feature isn't yet available.  I don't have time at the moment to devote to this so if you guys can give it a go and let me know that would be great.

**Comment by tanczosm** [comment]
Pushing a new version that is using the graduated version of the API call from experimental to permissions.  Most methods are named CheckBulk* instead of BulkCheck*

**Comment by amadard** [comment]
> Pushing a new version that is using the graduated version of the API call from experimental to permissions. Most methods are named CheckBulk* instead of BulkCheck*

AuthZed confirmed that CheckBulk is the GA release of the BulkCheck.

**Comment by tanczosm** [comment]
> > Pushing a new version that is using the graduated version of the API call from experimental to permissions. Most methods are named CheckBulk* instead of BulkCheck*
> 
> AuthZed confirmed that CheckBulk is the GA release of the BulkCheck.

Sounds good.  Then I'm going to try again to test when I get off of work.  If it does work for you let me know.

**Comment by amadard** [comment]
> > > Pushing a new version that is using the graduated version of the API call from experimental to permissions. Most methods are named CheckBulk* instead of BulkCheck*
> > 
> > 
> > AuthZed confirmed that CheckBulk is the GA release of the BulkCheck.
> 
> Sounds good. Then I'm going to try again to test when I get off of work. If it does work for you let me know.

I asked about CheckBulk and Serverless, this is the response:
We don't ever plan to implement that API in Serverless. We are deprecating Serverless in a few months in favor of Authzed Cloud. BulkCheck will be available in Authzed Cloud. If you want to test BulkCheck, you can run SpiceDB in a Docker container.

**Comment by tanczosm** [comment]
So it seems that in order for me to test this method I'm going to need to set up a server. I've largely been going off Serverless for testing purposes but it appears a number of newer API methods aren't implemented in Serverless anyway.

**Comment by tanczosm** [comment]
I set up a proper environment for testing and have testing working through Github actions as well.  I was able to successfully get bulk permission testing to work in the newest version.
