### ISSUE TITLE
Remove usage of deprecated Grpc.Core

### ISSUE THREAD

**Issue by epbensimpson** [JalexSocial/SpiceDb#14]
I was having a look at what it would take to remove the direct reference to `Grpc.Core` as it is deprecated and also prevents using this library on Apple Silicon (can't find `libgrpc_csharp_ext.arm64.dylib`). It looks like it's only used to create the insecure channel:

https://github.com/JalexSocial/SpiceDb/blob/44383bc127c75896d5797134c0d2747525b26f05/SpiceDb/Api/Core.cs#L74-L78

Unless I'm missing something, it seems like all that should be required is to switch that to:

```csharp
 if (address.StartsWith("http:"))
{
    channel = GrpcChannel.ForAddress(address);
}
```

According to [the docs](https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-8.0#call-insecure-grpc-services-with-net-core-client) this should be supported by the version of `Grpc.Net.Client` being used.

**Comment by tanczosm** [comment]
I agree that after I made some of the latest changes we could really streamline this process.  Technically we should really just need a ChannelBase and CallOptions (?) to be created. 

I pushed out a new version for you to experiment with.  It passed all the current tests.

**Comment by tanczosm** [comment]
I refactored the code a bit for 1.5.0 and cleaned up a lot.  I removed Grpc.Core completely and also exposed a new way to create SpiceDbClient clients using just a ChannelBase.  The new default ChannelBase configuration is as follows:

```csharp
	private ChannelBase CreateDefaultAuthenticatedChannel(string address, string? token)
	{
		var credentials = CallCredentials.FromInterceptor((context, metadata) =>
		{
			if (!string.IsNullOrEmpty(token))
			{
				metadata.Add("Authorization", $"Bearer {token}");
			}
			return Task.CompletedTask;
		});

		//Support proxy by setting webproxy on httpClient
		HttpClient.DefaultProxy = new WebProxy();

		var isSecure = address.StartsWith("https://");

		// SslCredentials is used here because this channel is using TLS.
		// CallCredentials can't be used with ChannelCredentials.Insecure on non-TLS channels.
		var channel = GrpcChannel.ForAddress(address, new GrpcChannelOptions
		{
			Credentials = ChannelCredentials.Create(isSecure ? ChannelCredentials.SecureSsl : ChannelCredentials.Insecure, credentials),
			UnsafeUseInsecureChannelCallCredentials = !isSecure
		});
		
		return channel;
	}
```
