### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by 64J0** [JalexSocial/SpiceDb#15]
Hello, hope you're good. I'm having some trouble using the `DeleteRelationshipsAsync` and I'd like to debug it. Is there a way to inspect the query that is going to be generated?

Update:

I'm using SpiceDb nuget package version 1.4.3. Will test the most recent version 1.5.0. With this new version, it's still not working here.

**Comment by 64J0** [comment]
I noticed that we receive a token information. Is it possible to use this data to debug the query?

**Comment by tanczosm** [comment]
Can you share the code you used to call the library and the error you received?

**Comment by 64J0** [comment]
Hi @tanczosm, thanks for the fast reply.

I was using the playground to test the queries, and it was not updating the system accordingly, but in reality, it was. When looking at the AuthZed dashboard, I was able to assert that the data was deleted.

I thought the playground and the system shared the same data and relations, but they don't, actually.

I'll close this issue since the problem was my lacking of understanding of AuthZed platform.
