### ISSUE TITLE
Any plans to support support SpiceDb REST API interface in addition to GRPC?

### ISSUE THREAD

**Issue by alekbarszczewski** [JalexSocial/SpiceDb#23]
It seems this client can only connect with SpiceDb over GRPC, however SpiceDb also exposes REST API (in addition to GRPC) - any plans to add REST API integration here?

**Comment by tanczosm** [comment]
Why might you end up choosing REST over GRPC for something that could be called as frequently as a permissions call?

**Comment by alekbarszczewski** [comment]
To be honest I wanted to host SpiceDB on heroku which does not support GRPC yet (they are working on supporting end-to-end HTTP2 but it can take a year or something) and this is why I am asking. I am aware that GRPC is much faster and lightweight and it would be my first choice if it was possible.

**Comment by tanczosm** [comment]
I'm closing this for now. This is a project that can be up for grabs if you want to implement a layer between the service interface that can make the calls.  As for me it's just not something I have the time to implement.
