### ISSUE TITLE
`LookupSubjects()` throwing `NullReferenceException` when there are subjects in response

### ISSUE THREAD

**Issue by hannesnisula** [JalexSocial/SpiceDb#4]
Using the NuGet package of version 1.3.8 in .NET 7.
When iterating over the `IAsyncEnumerable<LookupSubjectsResponse>` with a foreach loop, the first iteration throws. As such:

```csharp
var subjectPageable =_spiceDbClient.LookupSubjects(
    new ResourceReference("asset", "device1"),
    "delete",
    "user");

await foreach (var subject in subjectPageable)
{
    // do anything or nothing
}
```
it throws a `System.NullReferenceException` and my best guess is that the `Current` property being `null` that causes the issue.
None of the arguments I pass to the method are `null`.

The iterator looks like this just before the exception:
![image](https://github.com/JalexSocial/SpiceDb/assets/7388814/3dd12683-5851-40c4-be9f-849fe671744e)

_Note: When there are no results it works as expected._

**Comment by tanczosm** [comment]
I found a potential null issue with the returned response in PartialCaveatInfo field. Can you update to 1.4.0 and try again?  I just published so it may be a few moments for it to be indexed on nuget.

**Comment by hannesnisula** [comment]
1.4.0 works. Thank you for the quick fix!
