### ISSUE TITLE
Authorization fails for DeleteRelationshipsAsync for secure connection

### ISSUE THREAD

**Issue by epbensimpson** [JalexSocial/SpiceDb#8]
Have run into an issue using secure connections where `DeleteRelationshipsAsync` is throwing the following:

```
Grpc.Core.RpcException: Status(StatusCode="PermissionDenied", Detail="invalid preshared key: invalid token")
   at async Task<ZedToken> SpiceDb.Api.Core.DeleteRelationshipsAsync(string resourceType, string optionalResourceId, string optionalRelation, string optionalSubjectType, string optionalSubjectId, string optionalSubjectRelation, RepeatedField<Precondition> optionalPreconditions, DateTime? deadline, CancellationToken cancellationToken)
   at async Task<ZedToken> SpiceDb.SpiceDbClient.DeleteRelationshipsAsync(RelationshipFilter resourceFilter, RelationshipFilter optionalSubjectFilter, List<Precondition> optionalPreconditions, DateTime? deadline, CancellationToken cancellationToken)
```

The client is definitely configured with the correct key as other operations (`WriteRelationships`, `CheckPermission`, `ReadRelationships`) are working fine.

Our integration tests which use an insecure connection were working fine, but after deploying to an environment that uses a secure connection the exception was thrown. 

I've had a dig into the code as to what might be causing this and I suspect that this was broken by #6 (kinda ironic if so 🙃). I haven't been able to confirm but I _think_ because `_headers` is being added in addition to the `CallCredentials` when it's `HTTPS`, it's duplicating the `Authorization` header or something. This would explain why the other API calls are not affected as they all just supply `_callOptions` instead of `_headers`.

If that's the case it seems like this might be resolved by leaving `_headers` as `null` when it's an `HTTPS` connection? i.e. move the setting of this variable into the `if (_serverAddress.StartsWith("http:"))` block.

**Comment by tanczosm** [comment]
Your take looks very feasible.  I'm not in a position to test this right now but with CreateAuthenticatedChannelAsync adding the Authorization bearer token that could definitely be what's going on.  The initial clients all add bearer tokens for https only so the callOptions would contain duplicate tokens for those that use the call options.  But even with that some of the calls can also include _headers directly (which should be null in most cases for https).  I'm going to need to revisit this at some point but i'm going to publish an update with this change.  

If it works please let me know.

**Comment by tanczosm** [comment]
I refactored the code a bit for 1.5.0 and cleaned up a lot.  I removed Grpc.Core completely and also exposed a new way to create SpiceDbClient clients using just a ChannelBase.  The new default ChannelBase configuration is as follows:

```csharp
	private ChannelBase CreateDefaultAuthenticatedChannel(string address, string? token)
	{
		var credentials = CallCredentials.FromInterceptor((context, metadata) =>
		{
			if (!string.IsNullOrEmpty(token))
			{
				metadata.Add("Authorization", $"Bearer {token}");
			}
			return Task.CompletedTask;
		});

		//Support proxy by setting webproxy on httpClient
		HttpClient.DefaultProxy = new WebProxy();

		var isSecure = address.StartsWith("https://");

		// SslCredentials is used here because this channel is using TLS.
		// CallCredentials can't be used with ChannelCredentials.Insecure on non-TLS channels.
		var channel = GrpcChannel.ForAddress(address, new GrpcChannelOptions
		{
			Credentials = ChannelCredentials.Create(isSecure ? ChannelCredentials.SecureSsl : ChannelCredentials.Insecure, credentials),
			UnsafeUseInsecureChannelCallCredentials = !isSecure
		});
		
		return channel;
	}
```

**Comment by tanczosm** [comment]
The creation of grpc channels was factored in an extensive way that this shouldn't be an issue any longer.  I'm closing this issue for now.
